### ISSUE TITLE
Extra \endgroup. \begin{document} and Extra }, or forgetten \endgroup, +

### ISSUE THREAD

**Issue by itfeature** [tweh/menukeys#61]
I am stuck with the error message "Extra \endgroup. \begin{document}". The error occurs when I use `menukeys` package. 

```
    \documentclass[12pt, oneside]{book}
\usepackage[a4paper, left=.7in, right=.7in, top=.7in,  bottom=.6in, footskip=.25in]{geometry}
\usepackage{color, xcolor}
\usepackage[T1]{fontenc}
\usepackage{multirow}

\usepackage{enumitem}
\setlist{noitemsep,topsep=0pt,parsep=0pt,partopsep=0pt,labelindent=1em,labelsep=10pt,leftmargin=*}

\usepackage{listings}
\newcommand{\rfunc}[1]{\lstinline{#1}}  %% Short for 'R inline'
\lstset{language=R}

\lstset{ %
    backgroundcolor=\color{white},  
    basicstyle=\small\ttfamily,
    breakatwhitespace=false,          % sets if automatic breaks should only happen at whitespace
    breaklines=true,                  % sets automatic line breaking
    %  captionpos=b,                    % sets the caption-position to bottom
    commentstyle=\color{black},       % comment style
    deletekeywords={...},             % if you want to delete keywords from the given language
    %  escapeinside={\%*}{*)},       % if you want to add LaTeX within your code
    %  extendedchars=true,           % lets you use non-ASCII characters; for 8-bits encodings only, does not work with UTF-8
    frame=single,                      % adds a frame around the code
    keepspaces=true, % keeps spaces in text, useful for keeping indentation of code (possibly needs columns=flexible)
    %  keywordstyle=\color{black},       % keyword style
    language=R,                      % the language of the code
    %  otherkeywords={*,...},          % if you want to add more keywords to the set
    numbers=left,                    % where to put the line-numbers; possible values are (none, left, right)
    %  numbersep=5pt,                  % how far the line-numbers are from the code
    %  numberstyle=\tiny\color{mygray},% the style that is used for the line-numbers
    rulecolor=\color{black},        
    %  showspaces=false,       % show spaces everywhere adding particular underscores; it overrides   'showstringspaces'
    showstringspaces=false,    % underline spaces within strings only
    %  showtabs=false,         % show tabs within strings adding particular underscores
    %  stepnumber=2,           % the step between two line-numbers. If it's 1, each line will be numbered
    stringstyle=\color{black}, % string literal style
    tabsize=2           % sets default tabsize to 2 spaces
}

\usepackage[os=win]{menukeys}
\renewmenumacro{\directory}{pathswithfolder}

\begin{document}
    
\begin{lstlisting}
> xyplot(mpg ~ wt | factor(vs, levels = c(0, 1), 
+    labels = c("vs = 0", "vs = 1")), data = mtcars, 
+    type = c("p"), pch = 19,
+    panel = function( ... ){
+       panel.xyplot( ... )
+       panel.grid(... , h = -1, v = -1)
+       panel.loess( ... )} )
\end{lstlisting}

\end{document}
![image](https://user-images.githubusercontent.com/10448374/98072728-82932900-1e88-11eb-8d0b-2863c47afce6.png)

Please Help in this regard.
```

**Comment by Skillmon** [comment]
This issue occurs because up until version 1.6 `menukeys` required the `catoptions` package, which is no longer compatible with the LaTeX kernel from 2020-10-01 onward.

This issue is fixed with version 1.6 which is already on CTAN and in MikTeX and TeX Live. Please update your local LaTeX installation.

**Comment by itfeature** [comment]
But I have installed the latest MikText distribution and menukeys package. Still getting the same error.

**Comment by itfeature** [comment]
But I have installed the latest MikText distribution and menukeys package. Still getting the same error.

**Comment by Skillmon** [comment]
The new version was included on 2020-11-03 at 9:11 pm. So if you haven't updated since you don't have the latest package version installed.

Could you please update your MikTeX installation. If the issue persists, could you please include `\listfiles` in your preamble and show me the resulting `*File List*` section from your log?

**Comment by Skillmon** [comment]
@itfeature just to make sure, is everything working for you now?
